# Generated by Django 3.2.15 on 2022-11-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('Директор', 'Директор'), ('Бухгалтер', 'Бухгалтер'), ('Менеджер', 'Менеджер'), ('Електрик', 'Електрик'), ('Сантехник', 'Сантехник'), ('Владелец квартиры', 'Владелец квартиры')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Активен', 'Активен'), ('Новый', 'Новый'), ('Отключен', 'Отключен')], max_length=10),
        ),
    ]
