# Generated by Django 3.2.15 on 2022-11-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221102_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='receipts',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='tariffs',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким логином уже существует!'}, max_length=254, unique=True),
        ),
    ]
