# Generated by Django 3.2.15 on 2022-11-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221106_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('Директор', 'Директор'), ('Бухгалтер', 'Бухгалтер'), ('Управляющий', 'Управляющий'), ('Электрик', 'Электрик'), ('Сантехник', 'Сантехник'), ('Владелец квартиры', 'Владелец квартиры')], max_length=20),
        ),
    ]
