# Generated by Django 3.2.15 on 2022-11-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_role_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('Директор', 'Директор'), ('Управляющий', 'Управляющий'), ('Бухгалтер', 'Бухгалтер'), ('Электрик', 'Электрик'), ('Сантехник', 'Сантехник'), ('Владелец квартиры', 'Владелец квартиры')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Активен', 'Активен'), ('Отключен', 'Отключен')], max_length=10),
        ),
    ]
