# Generated by Django 3.2.15 on 2023-01-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221125_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='purposes',
        ),
    ]
