# Generated by Django 3.2.15 on 2023-02-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
