# Generated by Django 3.2.15 on 2023-02-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
