# Generated by Django 3.2.15 on 2023-02-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_templates', '0002_exceltemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceltemplate',
            name='file',
            field=models.FileField(upload_to='excel_templates'),
        ),
    ]
