# Generated by Django 3.2.15 on 2023-01-06 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 6, 17, 17, 36, 638844)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 6, 17, 17, 50, 796335)),
            preserve_default=False,
        ),
    ]
