# Generated by Django 3.2.15 on 2023-01-10 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_application', '0002_auto_20230106_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 10, 23, 27, 4, 743464)),
            preserve_default=False,
        ),
    ]
