# Generated by Django 3.2.15 on 2023-01-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_application', '0003_application_date_add'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-pk']},
        ),
    ]
