# Generated by Django 3.2.15 on 2023-02-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_application', '0004_alter_application_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='master_type',
            field=models.CharField(choices=[('Сантехник', 'Сантехник'), ('Електрик', 'Електрик'), ('Любой мастер', 'Любой мастер')], default='', max_length=12),
            preserve_default=False,
        ),
    ]
