# Generated by Django 3.2.15 on 2023-02-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_application', '0005_application_master_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='master_type',
            field=models.CharField(choices=[('Любой специалист', 'Любой специалист'), ('Сантехник', 'Сантехник'), ('Электрик', 'Электрик')], max_length=16),
        ),
    ]
