# Generated by Django 3.2.15 on 2023-02-21 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_application', '0006_alter_application_master_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master', to=settings.AUTH_USER_MODEL),
        ),
    ]
