# Generated by Django 3.2.15 on 2022-11-02 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_service.unit'),
        ),
    ]
