# Generated by Django 3.2.15 on 2022-11-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0002_alter_service_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(error_messages={'unique': 'Услуга с таким именем уже существует!'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(error_messages={'unique': 'Единица измерения с таким именем уже существует!'}, max_length=50, unique=True),
        ),
    ]
