# Generated by Django 3.2.15 on 2022-12-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_apartment', '0003_alter_apartment_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Активен', 'Активен'), ('Неактивен', 'Неактивен')], max_length=9)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_apartment.apartment')),
            ],
        ),
    ]
