# Generated by Django 3.2.15 on 2022-12-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_personal_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
