# Generated by Django 3.2.15 on 2022-12-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_personal_account', '0002_personalaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
