# Generated by Django 3.2.15 on 2023-01-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apartment', '0003_alter_apartment_house'),
        ('admin_personal_account', '0004_alter_personalaccount_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='apartment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_apartment.apartment'),
        ),
    ]
