# Generated by Django 3.2.15 on 2023-06-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_purpose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='transaction_type',
            field=models.CharField(choices=[('Надходження', 'Надходження'), ('Витрата', 'Витрата')], max_length=11),
        ),
    ]
