# Generated by Django 3.2.15 on 2022-11-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_purpose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(error_messages={'unique': 'Статья с таким именем уже существует!'}, max_length=50, unique=True),
        ),
    ]
