# Generated by Django 3.2.15 on 2023-03-21 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admin_house", "0001_initial"),
        ("admin_apartment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="floor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admin_house.floor",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to="admin_house.house",
            ),
        ),
    ]
