# Generated by Django 3.2.15 on 2022-12-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_house', '0003_auto_20221125_1819'),
        ('admin_apartment', '0002_alter_apartment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='admin_house.house'),
        ),
    ]
