# Generated by Django 3.2.15 on 2023-02-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_messages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
