# Generated by Django 3.2.15 on 2023-02-08 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_house', '0003_auto_20221125_1819'),
        ('admin_apartment', '0003_alter_apartment_house'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_messages', '0002_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=78)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_apartment.apartment')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_house.floor')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_house.house')),
                ('receivers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_house.section')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
