# Generated by Django 3.2.15 on 2023-02-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_house', '0003_auto_20221125_1819'),
        ('admin_apartment', '0003_alter_apartment_house'),
        ('admin_messages', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_apartment.apartment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_house.floor'),
        ),
        migrations.AlterField(
            model_name='message',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_house.house'),
        ),
        migrations.AlterField(
            model_name='message',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_house.section'),
        ),
    ]
