@startuml
!theme materia
title Create Application Activity Diagram


start
:Navigate to "Application create" page;

:Send GET request for "Application create" page;

:Retrieve list of available apartments and owners;
:Retrieve list of available master types;
:Render "Create Application" page with lists;

:Show "Create Application" page with lists;
:Select convenient date;
:Select convenient time;
:Select owner;
if(Owner selected?) then([Yes])
    :Send GET request for owner's apartment list;

    :Retrieve list of apartments for selected owner;
    :Send JSON response with owner's apartment list;

    :Fill apartment select field with received data;
else([No])
endif
:Select apartment;
:Fill description field;
:Select master type;
:Send GET request for master list with selected type;

:Retrieve list of masters with selected type;
:Send JSON response with master list with selected type;

:Fill master select field with received data;
:Select status;
:Fill comment field;
:Send POST request with application information;

:Validate application information;
:Create new Application instance with application information;
:Save new Application instance;
:Redirect user to "Application list" page;
:Send HTML response with "Application list" page;
stop
@enduml
