# Generated by Django 3.2.15 on 2022-12-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_apartment', '0003_alter_apartment_house'),
        ('admin_service', '0003_auto_20221109_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Новое', 'Новое'), ('Учтено', 'Учтено'), ('Учтено и оплачено', 'Учтено и оплачено'), ('Нулевое', 'Нулевое')], max_length=20)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_apartment.apartment')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_service.service')),
            ],
        ),
    ]
