# Generated by Django 3.2.15 on 2023-01-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_meter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='value',
            field=models.FloatField(),
        ),
    ]
