# Generated by Django 3.2.15 on 2023-01-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_meter', '0002_alter_meter_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['pk']},
        ),
    ]
