# Generated by Django 3.2.15 on 2023-01-11 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_personal_account', '0003_alter_personalaccount_number'),
        ('admin_purpose', '0002_alter_purpose_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField()),
                ('is_complete', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=50, unique=True)),
                ('comment', models.TextField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_owner', to=settings.AUTH_USER_MODEL)),
                ('persona_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_personal_account.personalaccount')),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_purpose.purpose')),
            ],
        ),
    ]
