# Generated by Django 3.2.15 on 2023-01-11 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_personal_account', '0003_alter_personalaccount_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_transaction', '0002_rename_persona_account_transaction_personal_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='personal_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_personal_account.personalaccount'),
        ),
    ]
