# Generated by Django 3.2.15 on 2023-01-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_transaction', '0003_auto_20230111_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
