# Generated by Django 3.2.15 on 2023-01-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_transaction', '0004_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-pk']},
        ),
    ]
