# Generated by Django 3.2.15 on 2022-11-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0003_auto_20221109_1238'),
        ('admin_tariff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='date_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='services',
            field=models.ManyToManyField(null=True, through='admin_tariff.TariffService', to='admin_service.Service'),
        ),
    ]
