# Generated by Django 3.2.15 on 2022-11-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0003_auto_20221109_1238'),
        ('admin_tariff', '0002_auto_20221116_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['-date_edit']},
        ),
        migrations.AlterField(
            model_name='tariffservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_service.service'),
        ),
    ]
