# Generated by Django 3.2.15 on 2022-11-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0003_auto_20221109_1238'),
        ('admin_tariff', '0003_auto_20221117_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='services',
            field=models.ManyToManyField(through='admin_tariff.TariffService', to='admin_service.Service'),
        ),
    ]
