# Generated by Django 3.2.15 on 2023-02-11 15:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('text', models.TextField()),
                ('site_url', models.URLField()),
                ('full_name', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('map_code', models.TextField()),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_website.seo')),
            ],
        ),
    ]
