# Generated by Django 3.2.15 on 2023-02-11 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_website', '0002_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(upload_to='website/main_page/blocks'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admin_website.seo'),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admin_website.seo')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website/service_page/blocks')),
                ('title', models.CharField(max_length=70)),
                ('text', models.TextField()),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_website.servicepage')),
            ],
        ),
    ]
