# Generated by Django 3.2.15 on 2023-02-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_website', '0004_tariffblock_tariffpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffblock',
            name='tariff_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_website.tariffpage'),
        ),
    ]
