# Generated by Django 3.2.15 on 2023-02-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_website', '0005_alter_tariffblock_tariff_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('text', models.TextField()),
                ('photo', models.ImageField(upload_to='website/about_page')),
                ('additional_title', models.CharField(max_length=70)),
                ('additional_text', models.TextField()),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admin_website.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website/about_page/gallery')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_website.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/about_page/documents')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_website.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='website/about_page/additional_gallery')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_website.aboutpage')),
            ],
        ),
    ]
