# Generated by Django 3.2.15 on 2023-02-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_website', '0006_aboutpage_additionalgallery_document_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
