# Generated by Django 3.2.15 on 2022-11-16 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='houses')),
                ('image2', models.ImageField(upload_to='houses')),
                ('image3', models.ImageField(upload_to='houses')),
                ('image4', models.ImageField(upload_to='houses')),
                ('image5', models.ImageField(upload_to='houses')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_house.house')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_house.house')),
            ],
        ),
    ]
