# Generated by Django 3.2.15 on 2022-11-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_house', '0002_house_date_edit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-date_edit']},
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(error_messages={'unique': 'Дом с таким адресом уже существует!'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(error_messages={'unique': 'Дом с таким названием уже существует!'}, max_length=50, unique=True),
        ),
    ]
