# Generated by Django 3.2.15 on 2023-01-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_apartment', '0003_alter_apartment_house'),
        ('admin_tariff', '0004_alter_tariff_services'),
        ('admin_service', '0003_auto_20221109_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Оплачена', 'Оплачена'), ('Частично оплачена', 'Частично оплачена'), ('Не оплачена', 'Не оплачена')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_apartment.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField()),
                ('price_unit', models.FloatField()),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_receipt.receipt')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_service.service')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='services',
            field=models.ManyToManyField(through='admin_receipt.ReceiptService', to='admin_service.Service'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_tariff.tariff'),
        ),
    ]
