# Generated by Django 3.2.15 on 2023-01-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_receipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptservice',
            old_name='receipt_id',
            new_name='receipt',
        ),
        migrations.RenameField(
            model_name='receiptservice',
            old_name='service_id',
            new_name='service',
        ),
    ]
