# Generated by Django 3.2.15 on 2023-01-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_receipt', '0002_auto_20230122_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-pk']},
        ),
    ]
