# Generated by Django 3.2.15 on 2023-02-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_receipt', '0003_alter_receipt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
