# Generated by Django 3.2.15 on 2023-02-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_receipt', '0004_receipt_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
