# Generated by Django 3.2.15 on 2023-02-24 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_personal_account', '0005_alter_personalaccount_apartment'),
        ('admin_receipt', '0005_alter_receipt_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='apartment',
        ),
        migrations.AddField(
            model_name='receipt',
            name='personal_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    null=True, to='admin_personal_account.personalaccount'),
            preserve_default=False,
        ),
    ]
